# Documentation: https://roots.io/trellis/docs/mail/
mail_smtp_server: smtp.klarkdeblyn.me:587
mail_admin: admin@klarkdeblyn.me
mail_hostname: klarkdeblyn.me
mail_user: smtp_user
mail_password: "{{ vault_mail_password }}" # Define this variable in group_vars/all/vault.yml
